name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

  workflow_dispatch:

  workflow_call:

jobs:
  check-code:
    runs-on: ubuntu-latest
    name: 'Check code'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: npm ci
      - name: Prettier
        run: npm run prettier:check
      - name: Lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    name: 'Build'
    needs: [ check-code ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: npm ci
      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    name: 'Test'
    needs: [ build ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: npm ci
      - name: Test
        run: npm test
